-- Start using Firebase auth. User IDs are now strings generated by the service

ALTER TABLE "user_credentials" DROP CONSTRAINT user_credentials_user_id;
DROP TABLE "user_credentials";

ALTER TABLE "tokens" DROP CONSTRAINT user_fk;
DROP TABLE "tokens";

ALTER TABLE "lists" DROP CONSTRAINT lists_user_id_fk;
ALTER TABLE "lists" ALTER COLUMN user_id SET DATA TYPE VARCHAR;

-- Port the user metadata column to a new table
CREATE TABLE "users_metadata"(
 "user_id" VARCHAR PRIMARY KEY,
 "preferences" JSONB
);

ALTER TABLE "events" DROP CONSTRAINT events_user_fk;
ALTER TABLE "events" ALTER COLUMN user_id SET DATA TYPE VARCHAR;

ALTER TABLE "user_network_preferences" DROP CONSTRAINT user_network_preferences_user_id_fkey;
ALTER TABLE "user_network_preferences" ALTER COLUMN user_id SET DATA TYPE VARCHAR;

ALTER TABLE "user_thing_tags" DROP CONSTRAINT user_thing_actions_user_id_fkey;
ALTER TABLE "user_thing_tags" ALTER COLUMN user_id SET DATA TYPE VARCHAR;

DROP TABLE "users";