jobs:
  include:
    - stage: backend
      name: "backend"
      language: scala
      jdk: oraclejdk8
      scala: 2.12.6
      sudo: required
      services:
        - docker
      before_install:
        - docker pull postgres
      before_script: cd scala-server
      script: travis_retry sbt ++$TRAVIS_SCALA_VERSION compile test
    - stage: frontend
      name: "Frontend"
      language: node_js
      node_js: "8"
      sudo: required
      services:
        - docker
      before_install:
        - docker pull postgres
      script: ./travis.build.sh
      env:
        - JWT_SECRET=jwt_secret_for_testing_only
    - stage: deploy
      jdk: oraclejdk8
      scala: 2.12.6
      sudo: required
      services:
        - docker
      script: ./docker_push.sh

stages:
  - backend
  - frontend
  - name: deploy
    if: branch = master

# matrix:
#   include:
#     - language: scala
#       jdk: oraclejdk8
#       scala: 2.12.4
#       services:
#         - docker
#       before_install:
#         - docker pull postgres
#       sudo: required
#       before_script: cd scala-server
#       script: travis_retry sbt ++$TRAVIS_SCALA_VERSION compile test

#     - language: node_js
#       node_js: "8"
#       script: ./travis.build.sh
#       services:
#         - docker
#       before_install:
#         - docker pull postgres
#       sudo: required
#       env:
#         - JWT_SECRET=jwt_secret_for_testing_only

# branches:
#   only: 
#     - master

# deploy:
#   - provider: script
#     script: bash docker_push.sh
#     on:
#       jvm: oraclejdk8
#       branch: master