before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jobs:
  include:
    - stage: build
      name: "Backend"
      language: scala
      jdk: oraclejdk8
      scala: 2.12.6
      sudo: required
      services:
        - docker
      before_install:
        - docker pull postgres
      before_script: cd scala-server
      script: test 'tag IS blank' && travis_retry sbt ++$TRAVIS_SCALA_VERSION compile test
    - name: "Frontend"
      language: node_js
      node_js: "8.11.1"
      sudo: required
      services:
        - docker
      before_install:
        - docker pull postgres
      script: ./travis.build.sh
      env:
        - JWT_SECRET=jwt_secret_for_testing_only
    - stage: deploy
      jdk: oraclejdk8
      language: scala
      scala: 2.12.6
      sudo: required
      services:
        - docker
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: ./docker_push.sh
        on:
          repo: chrisbenincasa/teletracker
          all_branches: true
          tags: true

stages:
  - build
  - name: deploy
    if: (tag IS present OR branch = master) AND type != pull_request
