version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase...
  build:
    commands:
      - cd scraper/node && ./build-scrapers
artifacts:
  files:
    - scraper/node/build/scrapers.zip
  name: scrapers-out
  discard-paths: yes
