steps:
  - name: "gcr.io/$PROJECT_ID/teletracker-sbt-primed"
    args:
      [
        "-J-Xss8m",
        "clean",
        "compile",
        "server/assembly",
        "tasks/assembly",
        "server/docker",
      ]
    dir: "scala-server"
images:
  - "gcr.io/teletracker/server"
artifacts:
  objects:
    location: "gs://teletracker-build-artifacts"
    paths:
      [
        "scala-server/server/target/scala-2.12/server-assembly-0.1-SNAPSHOT.jar",
        "scala-server/tasks/target/scala-2.12/tasks-assembly-0.1-SNAPSHOT.jar",
      ]
timeout: 1800s
