steps:
  - name: "gcr.io/$PROJECT_ID/teletracker-server-primed"
    args: ["-J-Xss8m", "clean", "compile", "server/assembly", "server/docker"]
    dir: "scala-server"
images:
  - "gcr.io/teletracker/server"
artifacts:
  objects:
    location: "gs://teletracker-build-artifacts"
    paths:
      [
        "scala-server/server/target/scala-2.12/teletracker-assembly-0.1-SNAPSHOT.jar",
      ]
timeout: 1800s
