steps:
  # Decrypt the Github ssh key
  - id: berglas
    name: gcr.io/berglas/berglas
    env:
      - API_KEY=berglas://${_BUCKET_ID}/github-ssh?destination=/secrets/github-ssh
    args: ["exec", "--local", "--", "/bin/sh"]
    volumes:
      - name: "secrets"
        path: /secrets

  # Decrypt the base64 encoded ssh key
  - name: "gcr.io/cloud-builders/curl"
    entrypoint: "bash"
    args:
      - "-c"
      - base64 -d /secrets/github-ssh > /root/.ssh/id_rsa
    volumes:
      - name: "ssh"
        path: /root/.ssh
      - name: "secrets"
        path: /secrets

  # Produce a known_hosts file for ssh
  - name: gcr.io/teletracker/teletracker-sbt-primed
    entrypoint: bash
    args:
      - "-c"
      - "ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts"
    volumes:
      - name: ssh
        path: /root/.ssh

  # Set up git with key and domain.
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        # mv known_hosts /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    args:
      ["clone", "--depth", "1", "git@github.com:chrisbenincasa/teletracker.git"]
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/teletracker/jq"
    entrypoint: "/bin/bash"
    dir: "teletracker/terraform/qa"
    args: ["-c", "./replace_version ${_VERSION}"]

  - name: "gcr.io/teletracker/terraform"
    dir: "teletracker/terraform/qa"
    args: ["init"]

  - name: "gcr.io/teletracker/terraform"
    dir: "teletracker/terraform/qa"
    args: ["apply", "-var-file=current.json", "-auto-approve"]

  - name: "gcr.io/cloud-builders/git"
    args: ["config", "user.email", "cloudbuild@cloudbuild.gserviceaccount.com"]
    dir: "teletracker"

  - name: "gcr.io/cloud-builders/git"
    args: ["config", "user.name", "Google Cloud Build"]
    dir: "teletracker"

  - name: "gcr.io/cloud-builders/git"
    args: ["commit", "-am", '"Deployed version ${_VERSION} to server"']
    dir: "teletracker"

  - name: "gcr.io/cloud-builders/git"
    args: ["push", "git@github.com:chrisbenincasa/teletracker", "master"]
    dir: "teletracker"
    volumes:
      - name: "ssh"
        path: /root/.ssh

substitutions:
  _VERSION: ""
  _BUCKET_ID: teletracker-secrets
