version: '3.1'

services:
  proxy:
    image: 302782651551.dkr.ecr.us-west-2.amazonaws.com/teletracker/server-nginx:1.2
    restart: always
    ports:
      - 8080:80
      - 8081:443
    links:
      - server

  server:
    image: 302782651551.dkr.ecr.us-west-2.amazonaws.com/teletracker/server:latest
    restart: always
    ports:
      - 3001:3001
    environment:
      - "AWS_REGION=us-west-2"
    env_file:
      - .env