version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - cd codebuild
      - ./build.sh
  post_build:
    commands:
      - docker push 302782651551.dkr.ecr.us-west-1.amazonaws.com/teletracker-build/server:latest
