#!/usr/bin/env bash

set -uex

REGION=${1:-"us-west-2"}
REPO="302782651551.dkr.ecr.${REGION}.amazonaws.com"

aws ecr get-login-password \
    --region "${REGION}" \
| docker login \
    --username AWS \
    --password-stdin "${REPO}"