#!/usr/bin/env bash

VERSION=${1:-"$(date +%s).${SHORT_SHA:-$(git rev-parse --short HEAD)}"}

docker build \
    --build-arg version="$VERSION" \
    --tag 302782651551.dkr.ecr.us-west-2.amazonaws.com/teletracker/frontend:latest \
    --tag 302782651551.dkr.ecr.us-west-2.amazonaws.com/teletracker/frontend:${VERSION} \
    .