#!/usr/bin/env bash

echo "Cleaning staging area"

if [ -d "build/" ]; then rm -rf "build/"; fi

mkdir build

rsync -avq src/* build \
  --exclude=build/ \
  --exclude=node_modules/ \
  --exclude=.idea \
  --exclude=.vscode \
  --exclude=*.zip

pushd build || exit
yarn --prod

zip -q scrapers.zip index.js main.js package.json yarn.lock

zip -urq scrapers.zip hbo/whats-new -x "*.DS_Store"
zip -urq scrapers.zip hbo/catalog* -x "*.DS_Store"
zip -urq scrapers.zip hulu/changes -x "*.DS_Store"
zip -urq scrapers.zip hulu/catalog -x "*.DS_Store"
zip -urq scrapers.zip netflix -x "*.DS_Store"
zip -urq scrapers.zip unogs -x "*.DS_Store"
zip -urq scrapers.zip tmdb -x "*.DS_Store"
zip -urq scrapers.zip common -x "*.DS_Store"
zip -urq scrapers.zip wikidata -x "*.DS_Store"
zip -urq scrapers.zip node_modules -x "*.DS_Store"

popd || exit