#!/bin/bash

set -o errexit          # Exit on most errors (see the manual)
set -o errtrace         # Make sure any error trap is inherited
set -o nounset          # Disallow expansion of unset variables
set -o pipefail         # Use last non-zero exit code in a pipeline

if [ -d "out/" ]; then rm -rf "out/"; fi

mkdir out

certbot certonly \ 
    --config-dir out/ \ 
    --work-dir out/ \ 
    --logs-dir out/ \ 
    --manual \ 
    --preferred-challenges dns \ 
    --email chrisbenincasa@gmail.com \ 
    --agree-tos \ 
    -d local.teletracker.tv -d local.api.teletracker.tv
