env: standard
runtime: python27
service: default
threadsafe: true

handlers:
  - url: /static
    static_dir: build/static

  - url: /images
    static_dir: build/images

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
