#!/usr/bin/env bash

echo "Cleaning staging area"

if [ -d "out/" ]; then rm -rf "out/"; fi

mkdir out

if [ -d ".next/" ]; then rm -rf ".next/"; fi

VERSION="$(date +%s).${SHORT_SHA:-$(git rev-parse --short HEAD)}" \
  yarn run next-build || exit

cp serverless/lambda-handler.js out/index.js
cp serverless/next-aws-cloudfront.js out/ 

node tools/gen-manifest | jq -r -c '.defaultBuildManifest' > out/manifest.json

mkdir -p out/pages
cp -R .next/serverless/pages/* out/pages

pushd out || exit

zip -qr frontend-lambda.zip ./*

popd || exit