#!/bin/bash

./build-ssr || exit

aws --region=us-east-1 s3 cp out/frontend-lambda.zip s3://us-east-1-teletracker-artifacts/
aws --region us-east-1 s3 sync --exclude "*development/*" .next/static/ s3://ssr.qa.teletracker.tv/_next/static
aws --region us-east-1 s3 sync public/images s3://ssr.qa.teletracker.tv/images
aws --region us-east-1 s3 cp public/favicon.ico s3://ssr.qa.teletracker.tv/favicon.ico