#!/bin/bash

./build-ssr

aws --region=us-east-1 s3 cp out/frontend-lambda.zip s3://us-east-1-teletracker-artifacts/
aws --region us-east-1 s3 sync ".next/static/" s3://ssr.qa.teletracker.tv/_next/static
aws --region us-east-1 s3 sync "public/" s3://ssr.qa.teletracker.tv/public